### ISSUE TITLE
Can this by made to work without needing a custom flutter script (eg. just run the script from (sdk)/bin/flutter)?

### ISSUE THREAD

**Issue by DanTup** [canonical/flutter-snap#8]
Currently the VS Code extension has some very specific handling for the Flutter Snap package and includes invoking a custom Flutter script (from the Snap) instead of the one inside the SDK. When discussing supporting the Snap in Android Studio/IntelliJ, some questions came up about this that I don't know the answers to (as I have a limited understanding of how Snaps work). Ideally, editors wouldn't need package-manager-specific changes as there are many editors and many package managers.

For example, some questions:

- Why is the custom script required / what happens if we don't use it?
- Can any configuration it does/env variables it sets be done at install time instead?

cc @MarcusTomlinson

**Comment by MarcusTomlinson** [comment]
**Some background:**

This snap was developed to provide a much more convenient way to install and use the Flutter SDK on Linux.

By simply running:

`snap install flutter --classic`

You'll have all the dependancies you need to begin developing Flutter applications. From here you can run: `flutter create`, `flutter run`, etc. as normal to perform flutter tasks - no need to install any further dependancies such as CMake, Ninja, GLib etc.

The Flutter repo is stored under `$HOME/snap/flutter/common/flutter/`, but the actual flutter script (executed by the call to `flutter`) is installed with the snap under `/snap/flutter/current/flutter.sh`. This allows users to switch flutter versions as needed via their home directory, while taking advantage of the dev environment provided by the snap.

To get this working in VS Code, we needed the extension to detect whether the flutter snap is installed, and if so, be aware of the separate repo and script locations for execution.

Furthermore, because all snaps are installed at root-level, the Flutter repo can only be populated on first user run of the snap. We therefore must also check if the repo exists on startup, and initialise it if not.

**Why the custom script is required:**

The snap contains all build dependencies flutter needs, so we have to prep a bunch of environment variables on execution for them to be found (See: https://github.com/kenvandine/flutter-snap/blob/master/env.sh). We don't want these environment changes to be persistent - that would cause all kinds of problems for other applications - so we must perform them upon each launch, and only for that process.

One alternative could be to call flutter from `/snap/bin/flutter` - as is done by regular `flutter` calls in the terminal (`/snap/bin` being in PATH) - however, because the VS Code extension launches flutter as a daemon, the vscode snap is unable to grab the fd from the flutter snap (snap-to-snap). There’s an open bug for this:

https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1849753
(If this gets fixed it removes the need to know the precise location of the flutter snap script at least).

**Scaleability:**

On the point of "many editors and many package managers": sure, the former is an issue, but the latter is not. Snaps is the package manager, and it is standard across Linux platforms, so I'd say the current solution scales relatively well.

The way we saw it was, either the editor knows this one specific thing about the snap so that the user doesn't have to worry about installing various flutter build dependancies (CMake, Ninja, GLib etc.), or the editor knows less, and the user is expected to put the missing pieces together. The latter may scale better for editor code but provide a worse experience for users.

Of course, another option is to move the snap specifics into Flutter itself, and out of the editors - i.e. have `bin/flutter` in the SDK directory do all the correct env tweaking (either directly, or indirectly via the snap script). We could have our snap locally modify the flutter repo to do this, but snap awareness built into the flutter tooling itself would be far less fragile. I had my doubts initially that we'd be able to convinced the Flutter team to do this, but perhaps I was wrong.

**Comment by devoncarew** [comment]
Thanks for the detailed response!

> **Scaleability:**
> 
> On the point of "many editors and many package managers": sure, the former is an issue, but the latter is not. Snaps is the package manager, and it is standard across Linux platforms, so I'd say the current solution scales relatively well.

I think Danny is referring to multiple IDEs (VS Code, Android Studio / IntelliJ, ...) and multiple installers (snap, mac's homebrew, windows msi / Windows Package Manager, ...). We'd like to avoid having to encode installer / package manager specific info into each IDE.

> The way we saw it was, either the editor knows this one specific thing about the snap so that the user doesn't have to worry about installing various flutter build dependancies (CMake, Ninja, GLib etc.), or the editor knows less, and the user is expected to put the missing pieces together. The latter may scale better for editor code but provide a worse experience for users.

+1 - I definitely agree w/ trying to reduce the complexity and burden on the user.

> Of course, another option is to move the snap specifics into Flutter itself, and out of the editors - e.g. have `bin/flutter` in the SDK directory do all the correct env tweaking (either directly, or indirectly via the snap script). We could have our snap locally modify the flutter repo to do this, but snap awareness built into the flutter tooling itself would be far less fragile. I had my doubts initially that we'd be able to convinced the Flutter team to do this, but perhaps I was wrong.

If we have specific proposals, I think we can discuss changes to the Flutter SDK. The flutter tools team would like to avoid knowledge about specific package managers into the Flutter sdk. I think a useful path to pursue would be whether we could come up with a general purpose mechanism - configurability we could add to the Flutter sdk, and that the snap package could take advantage of, but not necessarily something which is snap specific.

Is the main problem to solve essentially how to add specific PATH and env variables to the `//bin/flutter` script when it runs? Something like (without endorsing this specific solution), having a file in `//bin/` that the `/bin/flutter` script could source if it existed, that could modify the env. variables before calling the rest of the script?

**Comment by MarcusTomlinson** [comment]
> Furthermore, because all snaps are installed at root-level (i.e. with no awareness of which user will actually use it), the Flutter repo can only be populated on first user run of the snap. This is quite transparent to a regular user. The first time you call `flutter run` for example, the snap script will first "initialise" (download) the SDK directory, then proceed immediately to executing the run command. From VS Code however, we must force this initialisation in advance as to ensure everything is in place before SDK detections begin (especially the detection of the Dart SDK which is within the Flutter one).

@devoncarew, there's a chicken and egg situation here ^. The flutter SDK can't be the first thing we call because it doesn't exist until the snap is executed for the first time.

Our `flutter.sh` script does 3 things:
1. Set up environment variables.
2. Download the flutter SDK (if doesn't exist).
3. Run `flutter`.

If we expect users to initialise the flutter snap themselves externally to any IDE before it'll work, then sure, all we need is some way to achieve 1. from `(sdk)/bin/flutter`.

**Comment by fcole90** [comment]
About 2, I wonder if it can be achieved just using a hook (like install hook): [[1](https://snapcraft.io/docs/supported-snap-hooks), [2](https://snapcraft.io/blog/snap-install-time-setup-the-install-hook)] rather than wait for the user to initialise it

**Comment by MarcusTomlinson** [comment]
@fcole90, snaps install as root, hooks and all.

**Comment by fcole90** [comment]
@MarcusTomlinson so, do you mean that the issue is that the SDK would end up being owned by the user `root`? If we knew the user who triggered the install we might `chown` to her user. Of course, this doesn't scale well in multi-user systems, as the other users would anyway need to set it up themselves; but would possibly work in the most typical scenario (single-user system) :thinking:

**Comment by MarcusTomlinson** [comment]
There are too many issues involved with this approach - users could be created after the snap is installed.  Home directories could be encrypted while the user is logged out.  Home directories might be auto-mounted network shares.  etc.

Honestly, I think the saner way forward is to just expect users to initiate the snap themselves after install. If we want to provide a better experience that doesn't require this (like VS Code has) then the IDE will need to have some knowledge of the snap (i.e. the entry point: `/snap/flutter/current/flutter.sh`).

**Comment by MarcusTomlinson** [comment]
@devoncarew @fcole90, ok, @DanTup had a great suggestion for this:

1. Have the IDE use `$PATH` to find the `flutter` command.
2. Implement a `flutter --sdk-path` command that returns the path to the SDK directory.
3. Have the IDE try `flutter --sdk-path` _first_, and only if nothing valid is returned, assume its relativity to the `flutter` executable.

Note however that step 2. will not be instantaneous if the sdk has not yet been downloaded by the snap. Some sort of progress indicator will be needed while this step processes.

At the time @DanTup brought this up, there was a [bug](https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1849753) that prevented this from working with IDE snaps, but I've just discovered a [possible workaround](https://github.com/kenvandine/flutter-snap/pull/11) that could put this back on the table.

What do you guys think?

**Comment by fcole90** [comment]
It seems it can work fine!

**Comment by DanTup** [comment]
> Have the IDE try `flutter --sdk-path` first, and only if nothing valid is returned, assume its relativity to the flutter executable

I think the concern with this approach is that IDEs could no longer pass just an SDK path around, they need to pass a pair of (SDK path + flutter script path). This is less Snap-specific than the current VS Code implementation, but it still requires some specific handling that editors generally won't do unless they specifically know about it (which for now, would probably be to specifically support Snap - though I do wonder if other tools like [fvm](https://github.com/leoafarias/fvm) might benefit from something like this).

A change was [landed](https://github.com/flutter/flutter/pull/62053) in Flutter that makes it easy to get the SDK path if we do end up going that route (or some variation of).

> Note however that step 2. will not be instantaneous if the sdk has not yet been downloaded by the snap. Some sort of progress indicator will be needed while this step processes.

First invocations of Flutter can be slow due to the Dart SDK download so editors should probably handle this somehow anyway. VS Code doesn't do a great job with this (it detects the SDK download in *some* situations), but it's something I'd like to improve.

**Comment by devoncarew** [comment]
Yeah, I think there are two general approaches being discussed here:

1 - Have the IDEs query the flutter tool for the real path of the Flutter sdk
- mentioned in https://github.com/kenvandine/flutter-snap/issues/8#issuecomment-671850924
- this means that the IDE clients need to invoke a flutter cli command (ala flutter --sdk-path) before calling any other flutter cli commands
- requires some work for existing IDEs and for each other IDE / tool to be aware of this convention

2 - have some way to embed the necessary env. variables into the flutter sdk itself
- this could be having the snap script modify <flutter-sdk>/bin/flutter (risky from a maintenance POV)
- enhance the flutter sdk so that it knows to load extra env. variables from a well-named file (<flutter-sdk>/bin/setup/bootstrap.sh ?)
- allows IDEs to use the flutter sdk as normal; it does mean that we may need user's to run the script once manually in order to finish setup

> If we expect users to initialise the flutter snap themselves externally to any IDE before it'll work ...

Sounds like a cost of going w/ option 2. It's good to know about this, but I don't think it's a blocker for this path - hopefully something that we can address well enough via documentation / getting started steps.

I lean towards 2) as an option, and am happy to help facilitate a discussion about flutter sdk changes (cc @jonahwilliams, @csells).

**Comment by jonahwilliams** [comment]
I don't really understand 2. We currently look for these executables on the PATH, so the proposal is to move this to separate environment environment variables. Why is setting a different environment variable easier than updating the PATH?

**Comment by MarcusTomlinson** [comment]
> **Why the custom script is required:**
> 
> The snap contains all build dependencies flutter needs, so we have to prep a bunch of environment variables on execution for them to be found (See: https://github.com/kenvandine/flutter-snap/blob/master/env.sh). We don't want these environment changes to be persistent - that would cause all kinds of problems for other applications - so we must perform them upon each launch, and only for that process.

@jonahwilliams, we’re referring to these ^ runtime environment variables.

**Comment by MarcusTomlinson** [comment]
> * enhance the flutter sdk so that it knows to load extra env. variables from a well-named file (/bin/setup/bootstrap.sh ?)

@devoncarew, I think this is the way to go here. How do you suggest we get this going?

**Comment by MarcusTomlinson** [comment]
> * enhance the flutter sdk so that it knows to load extra env. variables from a well-named file (/bin/setup/bootstrap.sh ?)

@devoncarew, I think this is the way to go here. How do you suggest we get going with this?

(cc @jonahwilliams, @csells, @stuartmorgan)

**Comment by jonahwilliams** [comment]
We could definitely load a bootstrap script at startup in the tool if it was present, format TBD?. This could be somewhere in `flutter/bin/internal` with a gitignore to avoid problems with untracked files.

**Comment by jonahwilliams** [comment]
thinking out loud: probably something simple like JSON. Then ideally the injected ProcessManager could be provided these without needing to plumb things around to the rest of the tooling.

**Comment by MarcusTomlinson** [comment]
> thinking out loud: probably something simple like JSON. Then ideally the injected ProcessManager could be provided these without needing to plumb things around to the rest of the tooling.

@jonahwilliams I'm battling to find a clean way to implement this. My first thought was to add an `environment` constructor variable to `LocalProcessManager` in process.dart, but it muddies up the implementation of the class a fair bit - we'd need new logic in each `run` and `start` method to combine custom and parent variables into `environment` as `includeParentEnvironment` would get ignored now. Do you think it's worth pursuing this route?

Another very (possibly overly) simple solution could be to have the known file be: `flutter/bin/internal/environment.txt` with format:

```
PATH=$SNAP/usr/bin:$SNAP/bin:$PATH
GIT_EXEC_PATH=$SNAP/usr/lib/git-core
GIT_CONFIG_NOSYSTEM=1
```

and add something like this to `flutter/bin/internal/shared.sh`:

```
if [ -f "$FLUTTER_ROOT/bin/internal/environment.txt" ]; then
  set -a
  . "$FLUTTER_ROOT/bin/internal/environment.txt"
  set +a
fi
```

Or perhaps, read from `flutter/bin/internal/environment.blah` and inject into the parent environment from dart at some entry point to the flutter tool - in `flutter_command.dart` perhaps?

Sorry to bug you. I'm happy to implement this of course, just need your expert opinion on how to best approach it. Thanks!

**Comment by jonahwilliams** [comment]
ship it

**Comment by jonahwilliams** [comment]
I think that doing it in the bash script, if it makes it significantly easier to maintain, is probably OK. Generally I like to avoid adding more code there, but provided there is some integration test somewhere covering it, it should be OK

**Comment by DanTup** [comment]
If this is intended to be more general than snap, the PowerShell script may need something similar? (so maybe rather than `.txt` it should be it should be `.sh` and the PoSh script could execute a `.ps1` version?).

**Comment by DanTup** [comment]
@MarcusTomlinson thanks! With these changes, is the SDK complete at snap-install time, or does the script still need to be invoked once to set things up?

**Comment by MarcusTomlinson** [comment]
> (My guess is the latter, which removes the need for the custom flutterRunScript config, but not the initial initialisation?)

This is correct. The snap will still require a first run to download the sdk.

**Comment by DanTup** [comment]
Got it, thanks! Which channel does the Snap package use? (I guess I shouldn't change anything until your Flutter change makes it to that channel).

**Comment by MarcusTomlinson** [comment]
@DanTup the snap downloads stable. The user is expected to call ‘flutter channel dev/master’ to select a channel other than stable. I believe this bootstrapping fix will only be available in master for the time being - in case you get questions about that.

**Comment by MarcusTomlinson** [comment]
> Which channel does the Snap package use?

We have told people to use the dev channel in our PR so chances are most people will be using that channel. If you remove the snap specific stuff now before the changes are in dev l, yeah, you’ll likely break a good number of people’s setups.
